\CREATE TABLE REC_RECEITA(
	rec_url VARCHAR(767) PRIMARY KEY,
	rec_nome VARCHAR(500) NOT NULL,
	rec_ingredientes TEXT NOT NULL,
	rec_modo_preparo TEXT,
	rec_html LONGTEXT NOT NULL 
)ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
DEFAULT CHARSET=utf8mb4;

CREATE FULLTEXT INDEX idx_rec_ingredientes ON REC_RECEITA(rec_ingredientes);

CREATE TABLE ALI_ALIMENTO(
	ali_nome VARCHAR(255) PRIMARY KEY
)ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
DEFAULT CHARSET=utf8mb4;

CREATE TABLE AIG_ALIMENTO_IG(
	aig_id INT AUTO_INCREMENT PRIMARY KEY,
	aig_nome VARCHAR(40) UNIQUE 
)ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;