CREATE TABLE REC_RECEITA(
	rec_id_receita INT AUTO_INCREMENT PRIMARY KEY,
	rec_url VARCHAR(767) UNIQUE,
	rec_url_imagem VARCHAR(767) NULL,
	rec_nome VARCHAR(500) NOT NULL,
	rec_ingredientes TEXT NOT NULL,
	rec_modo_preparo TEXT,
	rec_html LONGTEXT NOT NULL 
)ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
DEFAULT CHARSET=utf8mb4;

CREATE FULLTEXT INDEX idx_rec_ingredientes ON REC_RECEITA(rec_ingredientes);

CREATE TABLE ALI_ALIMENTO(
	ali_nome VARCHAR(255) PRIMARY KEY
)ENGINE=InnoDB
ROW_FORMAT=COMPRESSED
DEFAULT CHARSET=utf8mb4;

CREATE TABLE AIG_ALIMENTO_IG(
	aig_id_alimento INT AUTO_INCREMENT PRIMARY KEY,
	aig_nome VARCHAR(40) UNIQUE,
	aig_frequencia INT NOT NULL default 0,
	aig_informacoes TEXT
)ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAL_CORRELACAO_ALIMENTO(
	cal_id_correlacao INT AUTO_INCREMENT PRIMARY KEY,
	cal_id_alimento_a INT NOT NULL,
	cal_id_alimento_b INT NOT NULL,
	cal_frequencia INT NOT NULL default 0,
	CONSTRAINT FK_CORRELACAO_ALIMENTO_A FOREIGN KEY (cal_id_alimento_a) REFERENCES AIG_ALIMENTO_IG (aig_id_alimento),
	CONSTRAINT FK_CORRELACAO_ALIMENTO_B FOREIGN KEY (cal_id_alimento_b) REFERENCES AIG_ALIMENTO_IG (aig_id_alimento)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;


CREATE TABLE ING_INGREDIENTE(
	ing_id_ingrediente INT AUTO_INCREMENT PRIMARY KEY,
	ing_texto TEXT,
	ing_html TEXT,
	ing_id_alimento INT,
	ing_id_receita INT NOT NULL,
	CONSTRAINT FK_INGREDIENTE_ALIMENTO FOREIGN KEY (ing_id_alimento) REFERENCES AIG_ALIMENTO_IG (aig_id_alimento),
	CONSTRAINT FK_INGREDIENTE_RECEITA FOREIGN KEY (ing_id_receita) REFERENCES REC_RECEITA (rec_id_receita) ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;


CREATE TABLE IPR_INSTRUCAO_PREPARO(
	ipr_id_instrucao_preparo INT AUTO_INCREMENT PRIMARY KEY,
	ipr_id_receita INT NOT NULL,
	ipr_id_alimento INT,
	ipr_ordem INT,
	ipr_texto TEXT,
	CONSTRAINT FK_INSTRUCAO_PREPARO_ALIMENTO_IG FOREIGN KEY (ipr_id_alimento) REFERENCES AIG_ALIMENTO_IG (aig_id_alimento),
	CONSTRAINT FK_INSTRUCAO_PREPARO_RECEITA FOREIGN KEY (ipr_id_receita) REFERENCES REC_RECEITA (rec_id_receita) ON DELETE CASCADE
)ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;